INSERT INTO users (full_name, email, password, role, created_at) VALUES
('Admin User', 'admin@mindcare.com', 'admin123', 'admin', NOW()),
('Juan Dela Cruz', 'juan1@mindcare.com', 'password123', 'customer', NOW()),
('Maria Santos', 'maria2@mindcare.com', 'password123', 'customer', NOW()),
('Pedro Reyes', 'pedro3@mindcare.com', 'password123', 'customer', NOW()),
('Ana Lopez', 'ana4@mindcare.com', 'password123', 'customer', NOW()),
('Carlos Mendoza', 'carlos5@mindcare.com', 'password123', 'customer', NOW()),
('Liza Flores', 'liza6@mindcare.com', 'password123', 'customer', NOW()),
('Mark Villanueva', 'mark7@mindcare.com', 'password123', 'customer', NOW()),
('Jenny Cruz', 'jenny8@mindcare.com', 'password123', 'customer', NOW()),
('Paul Navarro', 'paul9@mindcare.com', 'password123', 'customer', NOW()),
('Erika Ramos', 'erika10@mindcare.com', 'password123', 'customer', NOW()),
('Nina Vergara', 'nina11@mindcare.com', 'password123', 'customer', NOW()),
('Leo Ramirez', 'leo12@mindcare.com', 'password123', 'customer', NOW()),
('Kim dela Rosa', 'kim13@mindcare.com', 'password123', 'customer', NOW()),
('Hannah Bautista', 'hannah14@mindcare.com', 'password123', 'customer', NOW()),
('Felix Mendoza', 'felix15@mindcare.com', 'password123', 'customer', NOW()),
('Roselle Tan', 'roselle16@mindcare.com', 'password123', 'customer', NOW()),
('Andrew Mallari', 'andrew17@mindcare.com', 'password123', 'customer', NOW()),
('Jasper Aquino', 'jasper18@mindcare.com', 'password123', 'customer', NOW()),
('Claire Sarmiento', 'claire19@mindcare.com', 'password123', 'customer', NOW()),
('Hiro Kato', 'hiro20@mindcare.com', 'password123', 'customer', NOW()),
('Mika Yamato', 'mika21@mindcare.com', 'password123', 'customer', NOW()),
('Allen Cruz', 'allen22@mindcare.com', 'password123', 'customer', NOW()),
('Diana Torres', 'diana23@mindcare.com', 'password123', 'customer', NOW()),
('Gino Velasco', 'gino24@mindcare.com', 'password123', 'customer', NOW()),
('Shaira Gomez', 'shaira25@mindcare.com', 'password123', 'customer', NOW());

INSERT INTO products (name, description, price, stock, created_at) VALUES
('Wellness Journal', 'Daily wellness tracker', 299.00, 100, NOW()),
('Meditation Kit', 'Candle + audio guide', 499.00, 50, NOW()),
('Stress Relief Balls', 'Anti-stress balls', 199.00, 150, NOW()),
('Aromatherapy Oil', 'Lavender oil', 350.00, 80, NOW()),
('Therapy Workbook', 'Guided workbook', 399.00, 60, NOW()),
('Mindfulness Cards', '30 reflection cards', 250.00, 100, NOW()),
('Sleep Aid Mask', 'Blackout sleep mask', 150.00, 200, NOW()),
('Relaxation Tea Set', 'Herbal calming tea', 220.00, 90, NOW()),
('Online Meditation Course', '4‑week program', 999.00, 9999, NOW()),
('Self‑Care Starter Pack', 'Wellness bundle', 799.00, 70, NOW());

INSERT INTO orders (user_id, total, order_date, status) VALUES
(2, 499.00, NOW(), 'paid'),
(3, 350.00, NOW(), 'completed'),
(4, 299.00, NOW(), 'paid'),
(5, 999.00, NOW(), 'pending'),
(6, 450.00, NOW(), 'completed'),
(7, 799.00, NOW(), 'paid'),
(8, 150.00, NOW(), 'completed'),
(9, 250.00, NOW(), 'pending'),
(10, 399.00, NOW(), 'paid'),
(11, 220.00, NOW(), 'completed');

INSERT INTO order_items (order_id, product_id, quantity, price) VALUES
(1, 2, 1, 499.00),
(2, 4, 1, 350.00),
(3, 1, 1, 299.00),
(4, 9, 1, 999.00),
(5, 5, 1, 399.00),
(6, 10, 1, 799.00),
(7, 7, 1, 150.00),
(8, 6, 1, 250.00),
(9, 3, 1, 199.00),
(10, 8, 1, 220.00);

INSERT INTO subscriptions (user_id, product_id, start_date, end_date, status) VALUES
(2, 9, '2025-01-01', '2025-02-01', 'active'),
(3, 9, '2025-01-05', '2025-02-05', 'active'),
(4, 9, '2025-01-08', '2025-02-08', 'expired'),
(5, 9, '2025-02-01', NULL, 'active'),
(6, 9, '2025-02-03', NULL, 'active'),
(7, 9, '2025-02-10', NULL, 'active'),
(8, 9, '2025-02-12', '2025-03-12', 'inactive'),
(9, 9, '2025-02-15', NULL, 'active'),
(10, 9, '2025-02-17', NULL, 'active'),
(11, 9, '2025-02-20', NULL, 'active');

INSERT INTO support_tickets (user_id, subject, message, status, created_at) VALUES
(2, 'Order Inquiry', 'Where is my order?', 'open', NOW()),
(3, 'Refund Request', 'I want a refund.', 'open', NOW()),
(4, 'Product Issue', 'The journal is damaged.', 'open', NOW()),
(5, 'Subscription Help', 'Cannot access course.', 'in_progress', NOW()),
(6, 'Account Issue', 'Cannot change password.', 'resolved', NOW()),
(7, 'Order Delay', 'Delivery late.', 'open', NOW()),
(8, 'Damaged Item', 'Tea set arrived broken.', 'open', NOW()),
(9, 'Wrong Item', 'Received wrong item.', 'open', NOW()),
(10, 'Payment Issue', 'Payment failed.', 'open', NOW()),
(11, 'Shipping Concern', 'Tracking not working.', 'open', NOW()),
(12, 'Refund Request', 'Requesting refund.', 'open', NOW()),
(13, 'Login Issue', 'Account locked.', 'in_progress', NOW()),
(14, 'Subscription Cancel', 'Cancel subscription.', 'resolved', NOW()),
(15, 'Order Inquiry', 'Where is my package?', 'open', NOW()),
(16, 'Product Concern', 'Oil bottle leaked.', 'open', NOW()),
(17, 'Account Update', 'Need to change email.', 'resolved', NOW()),
(18, 'Order Error', 'Ordered by mistake.', 'open', NOW()),
(19, 'Course Access', 'Course won’t load.', 'in_progress', NOW()),
(20, 'Delivery Issue', 'Package stuck.', 'open', NOW()),
(21, 'Payment Duplicate', 'Charged twice.', 'in_progress', NOW()),
(22, 'Product Inquiry', 'Is tea caffeine-free?', 'resolved', NOW()),
(23, 'Order Modification', 'Change address.', 'open', NOW()),
(24, 'Missing Item', 'Item missing.', 'open', NOW()),
(25, 'Subscription Help', 'How to renew?', 'open', NOW()),
(26, 'General Inquiry', 'Do you offer discounts?', 'open', NOW()),
(2, 'Follow-up', 'Any update?', 'open', NOW()),
(3, 'Extra Concern', 'Product not as expected.', 'open', NOW()),
(4, 'Technical Issue', 'Website error.', 'resolved', NOW()),
(5, 'Priority Request', 'Need urgent help.', 'in_progress', NOW());
